name: RSS generation

on:
  push:
    branches:
      - master
#on:
  #schedule:
    #- cron: '*/5 * * * *'  # Run every 10 minutes

jobs:
  gene-rss-bazaar:
    runs-on: ubuntu-latest
    name: A job to test RSS generation for Cafebazaar
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    # - name: Fetch Bazaar RSS
    #   uses: ./
    #   with:
    #     title: Fetch Bazaar RSS
    #     url: https://cafebazaar.ir/app/ir.tejaratbank.tata.mobile.android.tejarat
    #     target: bazaar
    #     item-title-css: .AppName
    #     item-url-css: .AppInstallBtn
    #     item-description-css: .InfoCubes
    #     last-version-css: .AppSubtitles__item
    #     active-users-css: tr:nth-child(1) > td.InfoCube__content.fs-14
    #     app-size-css: tr:nth-child(4) > td.InfoCube__content.fs-14
    #     release-date-css: tr:nth-child(5) > td.InfoCube__content.fs-14

    # - name: Fetch Anardoni RSS
    #   uses: ./
    #   with:
    #     title: Fetch Anardoni RSS
    #     url: https://anardoni.com/ios/app/comadytejaratbank
    #     target: anardoni
    #     item-title-css: h1
    #     item-url-css: h1
    #     item-description-css: h1
    #     last-version-css: head > script:nth-child(17)
    #     active-users-css: div:nth-child(3) > div.text-grey-7.fa-number-bold.size-5
    #     app-size-css: div:nth-child(5) > div.text-grey-7.fa-number-bold.size-5
    #     release-date-css: div:nth-child(9) > div.text-grey-7.fa-number-bold.size-5

    # - name: Fetch Myket RSS
    #   uses: ./
    #   with:
    #     title: Fetch Myket RSS
    #     url: https://myket.ir/app/ir.tejaratbank.tata.mobile.android.tejarat
    #     target: myket
    #     item-title-css: h1
    #     item-url-css: h1
    #     item-description-css: h1
    #     last-version-css: tr:nth-child(1) > td:nth-child(2)
    #     active-users-css: tr:nth-child(3) > td:nth-child(2)
    #     app-size-css: tr:nth-child(6) > td:nth-child(2)
    #     release-date-css: tr:nth-child(2) > td:nth-child(2)

    # - name: Fetch Sibirani RSS
    #   uses: ./
    #   with:
    #     title: Fetch Sibirani RSS
    #     url: https://sibirani.com/apps/7T5pwqdNGg/
    #     target: sibirani
    #     item-title-css: h1
    #     item-url-css: h1
    #     item-description-css: .slogan
    #     last-version-css: div.slder-new-section.mobile_scrin.app_intro_items > div > div > div:nth-child(7) > div.value > div
    #     active-users-css: div.slder-new-section.mobile_scrin.app_intro_items > div > div > div:nth-child(2) > div.value > div
    #     app-size-css: div.slder-new-section.mobile_scrin.app_intro_items > div > div > div:nth-child(5) > div.value > div
    #     release-date-css: .date

    - name: Fetch Charkhoneh RSS
      uses: ./
      with:
        title: Fetch Charkhoneh RSS
        url: https://www.charkhoneh.com/content/930667751
        target: charkhoneh
        item-title-css: head > script
        item-url-css: head > script
        item-description-css: head > script
        last-version-css: head > script
        active-users-css: head > script
        app-size-css: head > script
        release-date-css: head > script

    # - name: Fetch Sibbank RSS SPA
    # - name: Fetch Iapps RSS SPA
    # - name: Fetch Farsroid RSS Unofficial

