name: Test RSS generation

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes

jobs:
  gene-rss:
    runs-on: ubuntu-latest
    name: A job to test RSS generation
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test Rssify
      uses: ./
      with:
        title: Test Rssify
        url: https://cafebazaar.ir/app/ir.tejaratbank.tata.mobile.android.tejarat
        item-title-css: .AppName
        item-url-css: .AppInstallBtn
        item-description-css: .InfoCubes
        #item-date-css: .post-time
        #item-date-format: '%Y-%m-%d'
